[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gambit-template"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.4",
]
description = "Template Repo"
authors = [
  { name = "Aaron Berkhoff", email = "aaronberkhoff@outlook.com" } ]


[dependency-groups]
dev = [
  "pytest>=8.4.0",
  "pytest-cov>=7.0.0",
  "mypy>=1.16.0,<2.0.0",
  "pylint>=3.3.7",
  "black>=25.1.0",
  "pre-commit>=4.2.0",
  "pybind11==2.13.6",
  "pybind11-stubgen>=2.5.5",
  "setuptools >= 61",
  "setuptools_scm>=8.0",
  "ruff>=0.14.0",
]

# Setuptools configuration for editable installs
[tool.setuptools]
package-dir = {"" = "python"}

[tool.setuptools.package-data]
gambit_template = [
    "*.so",       # Linux/Mac extension
    "*.pyd",      # Windows extension
    "*.pyi",      # Type stubs
    "py.typed",   # PEP 561 marker
]

# This tells setuptools where to find packages
[tool.setuptools.packages.find]
where = ["python"]